# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: '~/angusfretwell'
email: angusfretwell@me.com
description: Angus is a web developer/designer from Melbourne, Australia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://angusfretwell.com" # the base hostname & protocol for your site
twitter_username: angusfretwell
github_username:  angusfretwell

# Build settings
markdown: kramdown
